# 相关配置说明
  # favicon: 网站图标
  # avatar: 主题用户头像与昵称
  # rss: rss订阅
  # gtag: Google 分析
  # comments: 文章评论系统
    # gitalk
    # disqus
  # navbar: 主题页面导航栏
  # catalog: 文章目录
  # prevnext: 文章末尾的上一页与下一页
  # friends: 友链
  # footer: 页脚信息
  # search: 文章搜索
  # colorSwitch: 深/浅配色切换
  # postShare: 文章分享
  # codeBlock: 代码块配置

# enable: 是否开启相应功能，可选true || false

# 网站图标
favicon:
  enable: true
  icon: /images/favicon.gif
  touch_icon: /images/favicon.gif

# 用户头像与昵称
avatar:
  author_photo: /images/avatar.gif
  author_nickname: zjlian
  path: /

# Google 分析
# https://analytics.google.com
# 注册Google分析账号，在管理/创建媒体资源/选择网站/填写相关信息后得到跟踪Id，一般格式为UA-xxxxxxx-x
# 如之前已有注册账号，在管理/跟踪信息/跟踪代码/找到跟踪ID，一般格式为UA-xxxxxxx-x
gtag:
  enable: false
  gtagkey: UA-xxxxxxx-x

# 文章评论系统
comments:
  enable: true
  # 目前仅支持gitalk, valine, disqus评论，选择喜欢的一种开启即可

  gitalk:
    # https://github.com/gitalk/gitalk#usage查看官方教程
    enable: false
    clientID:
    clientSecret:
    repo:
    owner:
    admin:
    id: location.pathname
    distractionFreeMode: false

  valine:
    # https://valine.js.org/quickstart.html#%E8%8E%B7%E5%8F%96APP-ID-%E5%92%8C-APP-Key
    # 进入以上网址查看官方教程
    enable: false
    appId:
    appKey:
    placeholder: Welcome!
    avatar: retro
    vempty_display: false

  # disqus 需科学上网方可使用
  disqus:
    # https://disqus.com/
    # 注册账号，获取shortname.disqus.com，shortname为你定义的唯一name
    # 例：我注册配置完毕后的网址为zxcxxxx.disqus.com，https-zxcxxxx-github-io即为shortname
    enable: false
    shortname: https-zxcxxxx-github-io
  
  # waline https://waline.js.org
  waline:
    enable: false
    serverURL:

# 主题页面导航栏
navbar:
  -
    name: 首页
    enable: true
    path: /
    key: home
  -
    name: 全部文章
    enable: true
    path: /archives/
    key: archives
  -
    name: 分类
    enable: true
    path: /categories/
    key: categories
  -
    name: 关于我
    enable: true
    path: /about/
    key: about
  -
    name: Tags
    enable: false
    path: /tags/
    key: tags
  -
    name: 友情链接
    enable: false
    path: /friends/
    key: friends


# 文章目录
catalog:
  enable: true

# 文章末尾的上一页与下一页
prevnext:
  enable: false

# 友链详细信息：支持多个友链
friends:
  # nickname: 昵称
  # site: 地址
  # meta: 描述

# 页脚信息
footer:
  # social: 社交方式
  # more: 更多页脚信息
  social:
    # name: 名称
    # icon: 图标，目前仅支持IconFont部分图标
    # path: 地址

    # 按需取消注释以启用
    -
      name: zjlian
      icon: github
      path: https://github.com/zjlian
    -
      name: TIDC
      icon: github
      path: https://github.com/TIDC
    # -
    #   name: facebook
    #   icon: facebooksquare
    #   path:
    # -
    #   name: twitter
    #   icon: twitter
    #   path:
    # -
    #   name: wechat
    #   icon: wechat
    #   path:
    # -
    #   name: weibo
    #   icon: weibo
    #   path:
    # -
    #   # rss需安装 hexo-generator-feed 插件
    #   # 具体参照https://github.com/hexojs/hexo-generator-feed
    #   name: rss
    #   icon: rss
    #   path: /atom.xml

  more:
    # 支持变量显示，可自定义扩展，具体见主题/layout/_partial/footer.ejs
    # 一般用来显示根据各种场景需要切换的文本，如时间年份
    # 如：{thisYear} 会被替换为今年年份
    -
      name: © {thisYear} (oﾟvﾟ)ノ ZJLIAN
      path: https://zjlian.github.io
    -
      name: 由 Hexo & Oranges 强力驱动
      path: https://github.com/zchengsite/hexo-theme-oranges

# 文章搜索
search:
  enable: true
  placeholder: 搜索...

# 深/浅配色切换
colorSwitch:
  enable: true

# 文章分享
postShare:
  enable: false

  twitter:
    enable: true

  facebook:
    enable: true

# 代码块配置
codeBlock:
  # 代码块风格，默认normal
  # 可选：默认风格'normal'；mac黑色风格：'mac-black'
  style: 'normal'
  # 代码复制
  copy:
    enable: true

# MathJax Support
# 数学公式支持
mathjax:
  enable: true

# cdn配置，默认关闭，如需启动，先确保对应插件版本cdn资源可用后再开启
# 如资源加载失败，可替换cdn提供商或设置enable:false默认走本地资源
# 也可使用自己的cdn服务，资源在/theme/oranges/source/plugins下
cdns:
  jquery:
    enable: false
    url: https://cdn.jsdelivr.net/npm/jquery@3.3.1/dist/jquery.min.js

  fancybox:
    enable: false
    url:
      css: https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css
      js: https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js

  # LaTeX 公式
  mathjax:
    enable: false
    url: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js

  # 代码块复制
  clipboard:
    enable: false
    url: https://cdn.jsdelivr.net/npm/clipboard@2.0.10/dist/clipboard.min.js

  # 评论系统
  comments:
    gitalk:
      enable: false
      url:
        css: https://cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.css
        js: https://cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.min.js

    valine:
      enable: false
      url: https://cdn.jsdelivr.net/npm/valine@1.4.18/dist/Valine.min.js

    waline:
      enable: false
      url: https://cdn.jsdelivr.net/npm/@waline/client@2.5.1/dist/legacy.min.js
